<a href="https://colab.research.google.com/github/daniyalaamir110/ML_course/blob/main/numpy_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.random.random_sample(4)

array([0.41563773, 0.10048462, 0.19049252, 0.93253632])

In [4]:
np.arange(4)

array([0, 1, 2, 3])

In [5]:
np.random.rand(4)

array([0.94162042, 0.49580847, 0.14339035, 0.34708235])

In [6]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a.shape

(10,)

In [9]:
a.dtype

dtype('int64')

In [10]:
a[1].shape

()

In [11]:
np.sum(a)

45

In [12]:
np.product(a[1:])

362880

In [13]:
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
b = np.arange(20, step=2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
a + b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
a * b

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [17]:
np.sum(a * b)

570

In [18]:
np.dot(a, b)

570

In [19]:
np.random.seed(1)

In [23]:
a = np.random.rand(10000000)
b = np.random.rand(10000000)

In [24]:
tic = time.time()
c = np.dot(a, b)
toc = time.time()

(toc - tic) * 1000

16.84403419494629

In [25]:
tic = time.time()
c = 0
for i in range(len(a)):
  c += a[i] * b[i]
toc = time.time()

(toc - tic) * 1000

6365.138053894043